#!/usr/bin/env bash
# Extract activations from the eval-aware scenarios generated by generate.sh.
# Requires GPU + model weights (no vLLM server needed -- this loads the model
# locally, unlike generation).

export CUDA_VISIBLE_DEVICES=4,5

set -euo pipefail

MODEL="Qwen/Qwen3-32B-AWQ"

SCENARIOS_CORE="data/scenarios/eval_aware/qwen3-32b-awq/core"
SCENARIOS_TRANSFER="data/scenarios/eval_aware/qwen3-32b-awq/transfer"
SCENARIOS_STEGO="data/scenarios/eval_aware/qwen3-32b-awq/stego"

ACTIVATIONS_CORE="data/activations/eval_aware/qwen3-32b-awq/core"
ACTIVATIONS_TRANSFER="data/activations/eval_aware/qwen3-32b-awq/transfer"
ACTIVATIONS_STEGO="data/activations/eval_aware/qwen3-32b-awq/stego"

echo "--- Extracting Core activations ---"
python extraction/extract_core.py --model "$MODEL" --runs-dir "$SCENARIOS_CORE" --output-dir "$ACTIVATIONS_CORE"

echo "--- Extracting Transfer activations ---"
python extraction/extract_transfer.py --model "$MODEL" --runs-dir "$SCENARIOS_TRANSFER" --output-dir "$ACTIVATIONS_TRANSFER"

echo "--- Extracting Stego activations ---"
python extraction/extract_stego.py --model "$MODEL" --runs-dir "$SCENARIOS_STEGO" --output-dir "$ACTIVATIONS_STEGO"

echo "=== Extraction complete. ==="
